version: '3.1'
services:
  springboot:
    image: 050228258667.dkr.ecr.ap-south-1.amazonaws.com/maven-web-application-docker:VERSION
    restart: always
    ports:
    - 9090:8080
    networks:
    - mavenappbridge
networks:
  mavenappbridge:
